services:
  db:
      image: mariadb:11
      container_name: gr2_db
      restart: always
      environment:
        MARIADB_ROOT_PASSWORD: hung1234
        MARIADB_DATABASE: gr2_hust
      ports:
        - "3306:3306"
      volumes:
        - gr2_db_data:/var/lib/mysql

volumes:
  gr2_db_data: